config/routes.rb
Rails.application.routes.draw do
  # root to: 'todo_items#index'
  resources :todo_items, only: [:index, :new, :create, :destroy, :update] do
    resources :completions, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo_item.rb
class TodoItem < ActiveRecord::Base
  def completed?
    completed_at?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/completions_controller.rb
class CompletionsController < ApplicationController
  def create
    todo_item = TodoItem.find(params[:todo_item_id])
    todo_item.update_attributes(completed_at: Time.now)
    redirect_to todo_items_path
  end
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  def index
    @todo_items = TodoItem.all
  end

  def new
    @todo_item = TodoItem.new
  end

  def create
    @todo_item = TodoItem.create(todo_item_params)
    redirect_to todo_items_path
  end

  def destroy
    TodoItem.find(params[:id]).destroy
    redirect_to todo_items_path
  end

  def update
    @todo_item = TodoItem.find(params[:id])
    @todo_item.update_attributes(complete: !@todo_item.complete?)
    redirect_to todo_items_path
  end

  private
  def todo_item_params
    params.require(:todo_item).permit(:title, :id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  def user_facing_flashes
    flash.to_hash.slice("alert", "error", "notice", "success")
  end
end

app/views/application/_analytics.html.erb
<% if ENV["SEGMENT_KEY"] %>
  <script type="text/javascript">
    window.analytics=window.analytics||[],window.analytics.methods=["identify","group","track","page","pageview","alias","ready","on","once","off","trackLink","trackForm","trackClick","trackSubmit"],window.analytics.factory=function(t){return function(){var a=Array.prototype.slice.call(arguments);return a.unshift(t),window.analytics.push(a),window.analytics}};for(var i=0;i<window.analytics.methods.length;i++){var key=window.analytics.methods[i];window.analytics[key]=window.analytics.factory(key)}window.analytics.load=function(t){if(!document.getElementById("analytics-js")){var a=document.createElement("script");a.type="text/javascript",a.id="analytics-js",a.async=!0,a.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n)}},window.analytics.SNIPPET_VERSION="2.0.9",
    window.analytics.load("<%= ENV["SEGMENT_KEY"] %>");
    window.analytics.page();
  </script>
<% end %>

app/views/application/_css_overrides.html.erb
<% if Rails.env.test? %>
  <style type="text/css">
    * {
      transition-property: none !important;
    }
  </style>
<% end %>

app/views/application/_flashes.html.erb
<% if flash.any? %>
  <div class="flashes">
    <% user_facing_flashes.each do |key, value| -%>
      <div class="flash-<%= key %>"><%= value %></div>
    <% end -%>
  </div>
<% end %>

app/views/application/_javascript.html.erb
<%= javascript_include_tag :application %>

<%= yield :javascript %>

<%= render "analytics" %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.fx.off = true;
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="ROBOTS" content="NOODP" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <%#
    Configure default and controller-, and view-specific titles in
    config/locales/en.yml. For more see:
    https://github.com/calebthompson/title#usage
  %>
  <title><%= title %></title>
  <%= stylesheet_link_tag :application, media: "all" %>
  <%= stylesheet_link_tag "https://fonts.googleapis.com/icon?family=Material+Icons" %>
  <%= stylesheet_link_tag "https://code.getmdl.io/1.3.0/material.indigo-pink.min.css" %>

  <script defer src="https://code.getmdl.io/1.3.0/material.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body class="<%= body_class %>">
  <%= render "flashes" -%>
  <%= yield %>
  <%= render "javascript" %>
  <%= render "css_overrides" %>
  <%= yield(:page_javascript) %>

</body>
</html>

app/views/todo_items/index.html.erb
<div class="mdl-layout mdl-js-layout">
  <main class="mdl-layout__content">
    <div class="page-content">
      <div class="todo-list">
        <ul class="todo-items mdl-list">
          <% @todo_items.each do |todo_item| %>
            <li class="todo-item mdl-list__item">
              <span class="mdl-list__item-primary-content js-todo-item">
                <i class="material-icons js-todo-list-item__checkbox unchecked"> ic_check_box_outline_blank </i>
                <%= todo_item.title %>
                <%= button_to todo_item_path(todo_item),
                  class: 'mdl-button mdl-js-button mdl-js-ripple-effect',
                  method: :delete, id: todo_item.id do %>
                  <i class="material-icons">ic_delete_forever</i>
                  Delete
                <% end %>

                <%= button_to todo_item_completions_path(todo_item),
                  class: "mdl-button mdl-js-button mdl-js-ripple-effect",
                  disabled: todo_item.completed?,
                  method: :create do %>
                  <%= "#{todo_item.completed? ? 'Done' : 'Mark as done'}" %>
                <% end %>
              </span>
            </li>
          <% end %>
        </ul>
      </div>
      <%= button_to 'Add item', new_todo_item_path,
        class: "mdl-button mdl-js-button mdl-button--raised",
        method: :get %>
    </div>
  </main>
</div>

<% content_for :page_javascript do %>
  <script type="text/javascript">
    $(function(){
      $('.js-todo-item').on('click', '.js-todo-list-item__checkbox', function(e){

        if ($(this).hasClass('unchecked')){
          $(this).toggleClass('unchecked').html("ic_check_box");
        } else {
          $(this).toggleClass('unchecked').html("ic_check_box_outline_blank");
        }
      });
    });
  </script>
<% end %>

app/views/todo_items/new.html.erb
<div class="mdl-layout mdl-js-layout">
  <main class="mdl-layout__content">
    <div class="page-content">
      <div class="mdl-layout-title"> Add item </div>
      <div class="mdl-grid">
        <%= simple_form_for @todo_item do |f| %>
          <%= f.input :title, wrapper: :mdl_field_floating %>
          <%= f.submit 'Add', class: 'mdl-button mdl-js-button mdl-button--raised' %>
        <% end %>
      </div>
    </div>
  </main>
</div>